Deploy the landing-page from github actions
Signed-off-by: Paul Schultz <pschultz@pobox.com>

diff --git a/.github/workflows/deploy-landing-page.yml b/.github/workflows/deploy-landing-page.yml
--- a/.github/workflows/deploy-landing-page.yml
+++ b/.github/workflows/deploy-landing-page.yml
@@ -12,19 +12,29 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 
-name: Deploy Landing Page
+name: Deploy Landing Page to Pages
+
 on:
+  # Runs on pushes targeting the default branch
   push:
-    branches:
-      - main
+    branches: [$default-branch]
+
+  # Allows you to run this workflow manually from the Actions tab
+  workflow_dispatch:
+
+# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
+permissions:
+  contents: read
+  pages: write
+  id-token: write
 
 concurrency:
   group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
   cancel-in-progress: true
 
 jobs:
-  main:
-    name: Main Job
+  build:
+    name: Build the Landing Page
     runs-on: ubuntu-latest
 
     env:
@@ -35,25 +45,68 @@ jobs:
 
     steps:
       - name: Checkout
-        uses: actions/checkout@v2
+      - uses: actions/checkout@v3
         with:
           fetch-depth: 0
 
       - name: Set SHA
         uses: nrwl/nx-set-shas@v2
 
-      - name: Install
+      - name: Detect package manager
+        id: detect-package-manager
         run: |
-          yarn install --frozen-lockfile
-
-      - name: Build
-        run: |
-          yarn nx affected --target=postexport --project=landing-page
-
-          # The export directory will only exist if there are changes to the landing page
-          if [ -d ./dist/apps/landing-page/exported ]; then
-            echo "is_new_build=true" >> $GITHUB_ENV
+          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
+            echo "::set-output name=manager::yarn"
+            echo "::set-output name=command::install"
+            echo "::set-output name=runner::yarn"
+            exit 0
+          elif [ -f "${{ github.workspace }}/package.json" ]; then
+            echo "::set-output name=manager::npm"
+            echo "::set-output name=command::ci"
+            echo "::set-output name=runner::npx --no-install"
+            exit 0
+          else
+            echo "Unable to determine packager manager"
+            exit 1
           fi
+
+      - name: Setup Node
+        uses: actions/setup-node@v3
+        with:
+          node-version: '16'
+          cache: ${{ steps.detect-package-manager.outputs.manager }}
+
+      - name: Setup Pages
+        uses: actions/configure-pages@v2
+        with:
+          # Automatically inject basePath in your Next.js configuration file and disable
+          # server side image optimization (https://nextjs.org/docs/api-reference/next/image#unoptimized).
+          #
+          # You may remove this line if you want to manage the configuration yourself.
+          static_site_generator: next
+
+      - name: Restore cache
+        uses: actions/cache@v3
+        with:
+          path: |
+            ./apps/landing-page/dist/.next/cache
+          # Generate a new cache whenever packages or source files change.
+          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-${{ hashFiles('./apps/landing-page/**.[jt]s', './apps/landing-page/**.[jt]sx') }}
+          # If source files changed but packages didn't, rebuild from a prior cache.
+          restore-keys: |
+            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-
+
+      - name: Install dependencies
+        run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}
+
+      - name: Build and Static HTML export with Nx
+        run: |
+          ${{ steps.detect-package-manager.outputs.runner }} nx run landing-page:postexport
+
+      - name: Upload artifact
+        uses: actions/upload-pages-artifact@v1
+        with:
+          path: ./apps/landing-page/dist/exported
 
       - name: Deploy to Branch
         uses: JamesIves/github-pages-deploy-action@v4
@@ -63,3 +116,15 @@ jobs:
           branch: master
           folder: dist/apps/landing-page/exported
           repository-name: devfile/devfile.github.io
+
+  deploy:
+    name: Deploy the Landing Page to Pages
+    environment:
+      name: github-pages
+      url: ${{ steps.deployment.outputs.page_url }}
+    runs-on: ubuntu-latest
+    needs: build
+    steps:
+      - name: Deploy to GitHub Pages
+        id: deployment
+        uses: actions/deploy-pages@v1
